version: '3'

services:
  php:
    build: ./docker/config/php
    image: laravel
    depends_on:
      - mysql
      - mysql-test
      - redis
    volumes:
      - ./src/:/application:cached

  horizon:
    build: ./docker/config/php
    image: laravel
    command: php artisan horizon
    depends_on:
      - mysql
    volumes:
      - ./src/:/application:cached

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    volumes:
      - "./.data/db:/var/lib/mysql"

  mysql-test:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./docker/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./src/:/application:cached
      - ./docker/server/nginx/:/var/log/nginx
    depends_on:
      - php

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  elk:
    image: willdurand/elk
    volumes:
      - ./docker/elk/logstash:/etc/logstash
      - ./docker/elk/logstash/patterns:/opt/logstash/patterns
    ports:
      - "8001:80"
      - "9200:9200"
      - "5046:5046"
volumes:
  db-data:
